#:kivy 1.0

<Animalsmediaplayer>:
	GridLayout:
		rows: 3
		cols: 3
		padding: 20
		spacing: 20
		MediaButton:
			on_press: root.button_pressed(root, self)
		MediaButton:
			on_press: root.button_pressed(root, self)
		MediaButton:
			on_press: root.button_pressed(root, self)
		MediaButton:
			on_press: root.button_pressed(root, self)
		MediaButton:
			on_press: root.button_pressed(root, self)
		MediaButton:
			on_press: root.button_pressed(root, self)
